language: php
php:
  - 7.0
  - 5.6

cache:
  directories:
  - vendor/

before_script: composer require --dev "phpunit/phpunit=5.7"

script: vendor/bin/phpunit Test/SluggoTest.php

notifications:
  email: false
